### ISSUE TITLE
Building error on OSX + Compile Request

### ISSUE THREAD

**Issue by Pigman168** [iBotPeaches/Apktool#1071]
My apologies in advance for the lengthy error log but I don't know what's relevant and what isn't. Anyways, I've posted it here: http://pastebin.com/BcjSrU0c
(Expiration: 1 month)

I've installed apktool as in the documentation athttp://ibotpeaches.github.io/Apktool/install/ for Mac OSX. The error is reproducible with the commands seen in the error log. The framework-res.apk is from a Kindle Fire (not HDX) and the APK I tried to de- and re-compile is called Forgotten Tales.

The file for the framework can be found here:
https://www.dropbox.com/s/8h064obnjiyxf6p/framework-res.apk?dl=0

and the file that I'm trying to recompile here:

https://www.dropbox.com/s/mmgk6k4wnaqr2nc/com.centralbytes.forgottentales.zip?dl=0

If someone could compile that for me and upload it while the bug is being fixed I would be ever so grateful.

**Comment by iBotPeaches** [comment]
I think I fixed this already here - https://github.com/iBotPeaches/Apktool/commit/5e4bae05264e9f1ea1c969971d81d824558cd12f

As I compiled the apk fine locally. You can try this `apktool.yml` with your project and let me know - http://pastebin.com/AnJgjEdw

**Comment by Pigman168** [comment]
Same error unfortunately - I tried inserting a \ before the spaces in the file path in case that would cause the issue but no change. Thank you very much for your quick reply! If you've compiled it already would you mind uploading it? If it's too much of a hassle I understand. :)

**Comment by iBotPeaches** [comment]
Okay last try.

Try this one - http://pastebin.com/eVTvqX3c

**Comment by Pigman168** [comment]
Unfortunately still throws an error but a new & smaller one! Progress I'd say.

http://pastebin.com/MdMVnB8v

I know it's bad to give a man a fish instead of teaching him to fish but I can survive on this fish for a lifetime. Meaning: if you could compile the dropbox zip file above into an apk that would be a life-saver.

**Comment by Furniel** [comment]
Build log + apk file.
java -jar apktool.jar b -c com.centralbytes.forgottentales -o com.centralbytes.forgottentales.apk
I: Using Apktool 2.0.3-ed35a9-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
warning: string 'change_password' has no default translation.
warning: string 'copy_link_text' has no default translation.
warning: string 'current_password' has no default translation.
warning: string 'extra_100level' has no default translation.
warning: string 'extra_backpack' has no default translation.
warning: string 'extra_skin' has no default translation.
warning: string 'invalid_email' has no default translation.
warning: string 'notification_choose_skin' has no default translation.
warning: string 'notification_remove_player_confirmation' has no default translation.
warning: string 'notification_skills' has no default translation.
warning: string 'password_change_failed' has no default translation.
warning: string 'password_changed' has no default translation.
warning: string 'password_recover' has no default translation.
warning: string 'password_recovery_msg' has no default translation.
warning: string 'password_recovery_sent' has no default translation.
warning: string 'play_offline' has no default translation.
warning: string 'recovery_email' has no default translation.
warning: string 'share_link_text' has no default translation.
warning: string 'share_text' has no default translation.
warning: string 'wrong_login_password' has no default translation.
I: Copy original files...
I: Copy AndroidManifest.xml...
I: Copy META-INF...
I: Building apk file...
https://www.dropbox.com/s/0k7rarjpwlex5za/com.centralbytes.forgottentales.apk?dl=0

**Comment by Pigman168** [comment]
You sir, are a hero! :) Thank you very very much! Is there anything I could do in return?

**Comment by iBotPeaches** [comment]
Glad you got it solved via help. Closing this.
