### ISSUE TITLE
[BUG]W: aapt: brut.common.BrutException: brut.common.BrutException: Could not extract resource: /prebuilt/linux/aapt_64 (defaulting to $PATH binary) W: First type is not attr! W: aapt F 07-26 15:17:02 22687 22687 First type is not attr! brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 134): [aapt, p, --min-sdk-version, 24, --target-sdk-version, 31, --version-code, 747, --version-name, 4.1.1, --no-version-vectors, -F, /tmp/APKTOOL5985328665120459921.tmp, -0, resources.arsc, -0, gif, -0, png, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/X浏览器_4.1.1/res, -M, /root/X浏览器_4.1.1/AndroidManifest.xml]

### ISSUE THREAD

**Issue by huocai520** [iBotPeaches/Apktool#3225]
### Information
1. **Apktool Version (`apktool -version`)** -
2. **Operating System (Mac, Linux, Windows)** -
3. **APK From? (Playstore, ROM, Other)** -
4. **Java Version (`java --version`)** -

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`
He's always been like this. I've tried a lot of things.
W: aapt: brut.common.BrutException: brut.common.BrutException: Could not extract resource: /prebuilt/linux/aapt_64 (defaulting to $PATH binary)
W: First type is not attr!
W: aapt F 07-26 15:17:02 22687 22687 First type is not attr!
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 134): [aapt, p, --min-sdk-version, 24, --target-sdk-version, 31, --version-code, 747, --version-name, 4.1.1, --no-version-vectors, -F, /tmp/APKTOOL5985328665120459921.tmp, -0, resources.arsc, -0, gif, -0, png, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/X浏览器_4.1.1/res, -M, /root/X浏览器_4.1.1/AndroidManifest.xml]

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment]
This was fixed a long time ago. So I would update your apktool and try using `--use--aapt2` during build.

Hope that helps. Closing.

**Comment by huocai520** [comment]
I am using apktool v2.8.1 and it still has this problem.

I used --use --aapt2, but it doesn't seem to have this parameter.

**Comment by iBotPeaches** [comment]
Sorry - the stacktrace you posted is not aapt2 and I don't understand what you mean.

**Comment by huocai520** [comment]
My apktool is the latest version of v2.8.1, but I still have this problem. Is there any solution?
I just tried the parameter you mentioned, but there is no --use --aapt2 parameter in apktool.

**Comment by iBotPeaches** [comment]
It does. Please take a read of the documentation. https://apktool.org/docs/cli-parameters#build
