### ISSUE TITLE
Exception in thread "main" org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65565

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#877]
Original [issue 768](https://code.google.com/p/android-apktool/issues/detail?id=768) created by codehead0 on 2015-02-26T02:58:21.000Z:

> <b>What steps will reproduce the problem?</b>
> 1. My apk has about 7000 smali files in classes.dex
> 2. When repacking, I get the following exception

<b>What is the expected output? What do you see instead?</b>
Exception in thread &quot;main&quot; org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65565
    at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
    at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:312)
    at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:980)
    at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:759)
    at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:214)
    at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:192)
    at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:57)
    at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:41)
    at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:349)
    at brut.androlib.Androlib.buildSources(Androlib.java:289)
    at brut.androlib.Androlib.build(Androlib.java:275)
    at brut.androlib.Androlib.build(Androlib.java:250)
    at brut.apktool.Main.cmdBuild(Main.java:225)
    at brut.apktool.Main.main(Main.java:84)

<b>What version of the product are you using? On what operating system?</b>
RC3

<b>Please provide any additional information below.</b>

**Comment by guptadipanshu** [comment]
Did the issue get resolved with Apktool 2.0.2 . I'm hitting the dex limit for recompiling the smali files. 
Thanks

**Comment by JaspreetSinghXDA** [comment]
same issue here dont know

**Comment by sudam-chavan** [comment]
Getting same issue with 2.2.0. Any solution for this?

Exception in thread "main" org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65573
	at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
	at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:329)
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1027)
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:803)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:252)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:230)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:53)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:38)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:400)
	at brut.androlib.Androlib.buildSources(Androlib.java:331)
	at brut.androlib.Androlib.build(Androlib.java:287)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)

**Comment by Jasi2169** [comment]
see this man :- https://github.com/JesusFreke/smali/issues/301

i also got this issue ,anyway dont add any extra methods,
the trick which i used was that i changed the bytes from hex editor analyzed from ida and then fix adler and signed the apk no need to do with smali,as it is related with smali see link aobve

**Comment by birfincankafein** [comment]
I builded my application with gradle. After that I need to change something and rebuild I wan to try Apktool but it throws this exception. Still not fixed?

**Comment by birfincankafein** [comment]
I builded my application with gradle. And I decompiled it with apktool. After that I try to recompile it with apktool but it throws this exception. Still not fixed?

**Comment by Jasi2169** [comment]
@birfincankafein dont add any extra methods ,singke class can have 65773 methods just create a new smali2 folder and add method with different class name in that required package and invoke it

**Comment by lisleyanne20** [comment]
i also got these errors. Please help me fix the errors. Thank you.
The application could not be wrapped.
        org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Lcom/kms/kaltura/kmsapplication/views/RoundCornerButton$IconSide;->values()[Lcom/kms/kaltura/kmsapplication/views/RoundCornerButton$IconSide;
                org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:824)
                org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:267)
                org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:245)
                brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:61)
                brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
                brut.androlib.Androlib.buildSourcesSmali(Androlib.java:412)
                brut.androlib.Androlib.buildNonDefaultSources(Androlib.java:358)
                brut.androlib.Androlib.build(Androlib.java:300)
                com.microsoft.intune.mam.apppackager.utils.APKToolWrapper.encodeAPK(APKToolWrapper.java:166)
                com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:138)
                com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:200)
                com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:56)
        org.jf.util.ExceptionWithContext: Error while writing instruction at code offset 0x2
                org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1091)
                org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:820)
                org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:267)
                org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:245)
                brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:61)
                brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
                brut.androlib.Androlib.buildSourcesSmali(Androlib.java:412)
                brut.androlib.Androlib.buildNonDefaultSources(Androlib.java:358)
                brut.androlib.Androlib.build(Androlib.java:300)
                com.microsoft.intune.mam.apppackager.utils.APKToolWrapper.encodeAPK(APKToolWrapper.java:166)
                com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:138)
                com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:200)
                com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:56)
        org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65536
                org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
                org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:348)
                org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1051)
                org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:820)
                org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:267)
                org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:245)
                brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:61)
                brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
                brut.androlib.Androlib.buildSourcesSmali(Androlib.java:412)
                brut.androlib.Androlib.buildNonDefaultSources(Androlib.java:358)
                brut.androlib.Androlib.build(Androlib.java:300)
                com.microsoft.intune.mam.apppackager.utils.APKToolWrapper.encodeAPK(APKToolWrapper.java:166)
                com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:138)
                com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:200)
                com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:56)
Failed to delete the temp file: C:\Users\LISLEY~1.HIN\AppData\Local\Temp\IntuneAppWrappingTool-397044653737079019

**Comment by unfairDude** [comment]
> @birfincankafein dont add any extra methods ,singke class can have 65773 methods just create a new smali2 folder and add method with different class name in that required package and invoke it

I know this is from 5 years old but can you explain better?
I have to edit MainActivity, Spotify app already has like 6 smali folders how should I proceed?
